---

- name: Install additional packages
  apt: name={{item}} state=present
  with_items:
   - python-trove
   - python-troveclient
   - python-glanceclient
   - trove-common
   - trove-api
   - trove-taskmanager
   - trove-conductor

- name: Copy trove.conf file
  template: src=trove.conf dest=/etc/trove
  
- name: Copy trove-taskmanager.conf file
  template: src=trove-taskmanager.conf dest=/etc/trove
  
- name: Copy trove-conductor.conf file
  template: src=trove-conductor.conf dest=/etc/trove
  
- name: Copy api-paste.ini file
  template: src=api-paste.ini dest=/etc/trove

- name: Create Trove cache folder
  command: mkdir /var/cache/trove
  
- name: Change ownership of Trove cache folder
  command: chown trove /var/cache/trove